name: educational_app
description: A Flutter-based educational app with OTP authentication, profile setup, school/chapter selection, and PDF content viewing functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  syncfusion_flutter_pdfviewer: ^24.1.41
  cupertino_icons: ^1.0.6
  flutter_otp_text_field: ^1.1.1
  intl: ^0.18.1
  flutter_file_downloader: ^2.1.0
  archive: ^4.0.7
  supabase_flutter: ^2.8.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  